---
- name: Install fan controller
  hosts: main
  become: true
  roles:
    - role: m1dnight.nanocluster.fan_controller
      become: true

  tasks:
    - name: Debug username
      ansible.builtin.command:
        cmd: "whoami"
      changed_when: false
