---
- name: Set up all nanocluster nodes
  hosts: nodes

  pre_tasks:
    - name: Check the platform for the pinned Go binary. Ensures the pi's are running 64bit os.
      ansible.builtin.assert:
        that:
          - ansible_facts.system == 'Linux'
          - ansible_facts.architecture == 'aarch64'
        fail_msg: The node inventory currently pins the Linux ARM64 Go distribution.

  roles:
    - role: packages
      become: true

    - role: asdf
