---
galaxy_info:
  author: Christophe De Troyer
  description: Install asdf and language runtimes for the connecting user
  license: GPL-2.0-or-later
  min_ansible_version: "2.17"
dependencies:
  - role: geerlingguy.go
    become: true
