---
all:
  children:
    nodes:
      hosts:
        nanocluster1:
          ansible_host: nc1.localdomain
        nanocluster2:
          ansible_host: nc2.localdomain
        nanocluster3:
          ansible_host: nc3.localdomain
        nanocluster4:
          ansible_host: nc4.localdomain
        nanocluster5:
          ansible_host: nc5.localdomain
        nanocluster6:
          ansible_host: nc6.localdomain
        # Unplugged; uncomment when reconnected.
        # nanocluster7:
        #   ansible_host: nc7.localdomain
    fan_controller:
      hosts:
        nanocluster1:
