---
all:
  hosts:
    nanocluster:
      ansible_host: nanocluster.localdomain
    nanocluster1:
      ansible_host: nc1.localdomain
      ansible_user: pi
    nanocluster2:
      ansible_host: nc2.localdomain
      ansible_user: pi
    nanocluster3:
      ansible_host: nc3.localdomain
      ansible_user: pi
    nanocluster4:
      ansible_host: nc4.localdomain
      ansible_user: pi
    nanocluster5:
      ansible_host: nc5.localdomain
      ansible_user: pi
    nanocluster6:
      ansible_host: nc6.localdomain
      ansible_user: pi
    nanocluster7:
      ansible_host: nc7.localdomain
      ansible_user: pi
  children:
    nodes:
      hosts:
        nanocluster1:
        nanocluster2:
        nanocluster3:
        nanocluster4:
        nanocluster5:
        nanocluster6:
        nanocluster7:
    main:
      hosts:
        nanocluster1:
