#SPDX-License-Identifier: MIT-0
---
# tasks file for asdf

#----------------------------------------------------------------------------
# Install ASDF

# - name: remove existing asdf directory
#   ansible.builtin.file:
#     path: "{{ ansible_env.HOME }}/.asdf"
#     state: absent

- name: download asdf binary
  ansible.builtin.get_url:
    url: "https://github.com/asdf-vm/asdf/releases/download/v0.18.0/asdf-v0.18.0-linux-arm64.tar.gz"
    dest: "/tmp/asdf-linux-arm64.tar.gz"
    mode: "0644"

- name: extract asdf binary
  become: true
  ansible.builtin.unarchive:
    src: "/tmp/asdf-linux-arm64.tar.gz"
    dest: "/usr/local/bin"
    remote_src: true

#----------------------------------------------------------------------------
# Install plugins

- name: add erlang plugin
  ansible.builtin.command:
    cmd: "asdf plugin add erlang https://github.com/asdf-vm/asdf-erlang.git"
    creates: "{{ ansible_env.HOME }}/.asdf/plugins/erlang"

- name: add elixir plugin
  ansible.builtin.command:
    cmd: "asdf plugin add elixir https://github.com/asdf-vm/asdf-elixir.git"
    creates: "{{ ansible_env.HOME }}/.asdf/plugins/elixir"

- name: add python plugin
  ansible.builtin.command:
    cmd: "asdf plugin add python https://github.com/asdf-community/asdf-python.git"
    creates: "{{ ansible_env.HOME }}/.asdf/plugins/python"

#----------------------------------------------------------------------------
# Configure ASDF

- name: add asdf shims to PATH
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"'
    create: true
    state: present

#----------------------------------------------------------------------------
# Install elixir and erlang

# elixir
- name: install elixir version
  ansible.builtin.command:
    cmd: "asdf install elixir {{ elixir_version | default('1.17') }}"
  register: elixir_install_output

- ansible.builtin.debug:
    msg: "{{ elixir_install_output.stdout_lines }}"

# erlang
- name: install erlang version
  ansible.builtin.command:
    cmd: "asdf install erlang {{ erlang_version | default('27.0') }}"
  register: erlang_install_output

- ansible.builtin.debug:
    msg: "{{ erlang_install_output.stdout_lines }}"

# python
- name: install python version
  ansible.builtin.command:
    cmd: "asdf install python {{ python_version | default('3.10.0') }}"
  register: python_install_output

- ansible.builtin.debug:
    msg: "{{ python_install_output.stdout_lines }}"

# reshim
- name: reshim
  ansible.builtin.command:
    cmd: "asdf reshim"

- name: create tool-versions file
  ansible.builtin.copy:
    content: |
      erlang {{ erlang_version | default('28.0.1') }}
      elixir {{ elixir_version | default('1.17') }}
      python {{ python_version | default('3.10.0') }}
    dest: "{{ ansible_env.HOME }}/.tool-versions"
    mode: "0644"
# - name: remove lines
#   ansible.builtin.lineinfile:
#     path: "{{ ansible_env.HOME }}/.bashrc"
#     line: "{{ item }}"
#     create: true
#     state: absent
#   with_items:
#     - ". /home/pi/.asdf/completions/asdf.bash"
