#SPDX-License-Identifier: MIT-0
---
#---------------------------------------------------------------------------
# Install basic packages

- name: install aptitude
  become: true
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: install basic system packages
  become: true
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: true
  with_items: "{{ packages }}"

#---------------------------------------------------------------------------
# Locale

- name: ensure localisation files for '{{ config_system_locale }}' are available
  become: true
  locale_gen:
    name: "{{ config_system_locale }}"
    state: present

- name: get current locale and language configuration
  become: true
  command: localectl status
  register: locale_status
  changed_when: false

- name: parse 'lang' from current locale and language configuration
  become: true
  set_fact:
    locale_lang: "{{ locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | first }}"

- name: parse 'language' from current locale and language configuration
  become: true
  set_fact:
    locale_language: "{{ locale_status.stdout | regex_search('LANGUAGE=([^\n]+)', '\\1') | default([locale_lang], true) | first }}"

- name: configure locale to '{{ config_system_locale }}' and language to '{{ config_system_language }}'
  become: true
  command: localectl set-locale LANG={{ config_system_locale }} LANGUAGE={{ config_system_language }}
  changed_when: locale_lang != config_system_locale or locale_language != config_system_language