---
namespace: m1dnight
name: nanocluster
readme: README.md
version: 0.0.1
authors:
  - Christophe De Troyer
description: Common node provisioning and shared fan control for the nanocluster
license: [GPL-3.0-or-later]
tags: [linux, raspberry, infrastructure]
repository: https://github.com/m1dnight/nanocluster
