---
# SSH keys come from your SSH agent/config or --private-key.
ansible_user: pi

ssh_keys_users:
  - pi

# Public key only; the matching private key stays on your computer.
ssh_keys_public_key: >-
  ssh-rsa
  AAAAB3NzaC1yc2EAAAADAQABAAABAQDUCfuzfZ+BbcjxIp2diASupYjPWxsn7rp9GTD0UjVegqxMlTLG0rLwFKGW5NRJXlzoNrSCcj5SeedMJt9qHCcdbxBzH7Mk9183SekGhk2dguK08j2nnFyGf2v7dx1HS+rkvp9hOSPD74A8Mdk8Pnm/VXfZzKJDyBqVIEGM9ydfuSAC1CL9xQ50woei17GF2PN/igQHNOpxlcBg4HdtHGZ1H1M7DW9xB929x1arf6ZUE7yMb+QjvRe4Ngx5qRBXVlL7cYeVUGNrCWQC8oQi3hEFsd8ADUYM8qQRRbtcfiaudQSYphKkxYbsU0bnb07falPVRWQz7Zt/XRAvfODeu55D
  christophe@bloempot


erlang_setup_cookie: nanoclustercookies

erlang_setup_hosts: "{{ groups['nodes'] | map('extract', hostvars, 'ansible_host') | list }}"
