packages_add_list:
  - git
  - tmux
  - emacs-nox
  - nfs-client
  - tree
  - ncdu
  - net-tools
  - make
  # erlang deps
  - build-essential
  - autoconf
  - m4
  - libncurses5-dev
  - libwxgtk3.2-dev
  - libwxgtk-webview3.2-dev
  - libgl1-mesa-dev
  - libglu1-mesa-dev
  - libpng-dev
  - libssh-dev
  - unixodbc-dev
  - xsltproc
  - fop
  - libxml2-utils
  - libncurses-dev

asdf_plugins:
  - name: "erlang" # a plugin name
    repository: "https://github.com/asdf-vm/asdf-erlang.git" # a plugin repository, optional
    version: latest

  - name: "elixir"
    repository: https://github.com/asdf-vm/asdf-elixir.git
    version: latest # set as a global version, optional
