---
packages_add_list:
  - git
  - tmux
  - emacs-nox
  - nfs-common
  - tree
  - ncdu
  - net-tools
  - make
  # erlang deps
  - build-essential
  - libssl-dev
  - curl
  - ca-certificates
  - unzip
  - autoconf
  - m4
  - libwxgtk3.2-dev
  - libwxgtk-webview3.2-dev
  - libgl1-mesa-dev
  - libglu1-mesa-dev
  - libpng-dev
  - libssh-dev
  - unixodbc-dev
  - xsltproc
  - fop
  - libxml2-utils
  - libncurses-dev

asdf_plugins:
  - name: "erlang"
    repository: "https://github.com/asdf-vm/asdf-erlang.git"
    version: latest

  - name: "elixir"
    repository: https://github.com/asdf-vm/asdf-elixir.git
    version: latest
